
datasets:
    dataset: "CIFAR10"
    image_size: 32
    channels: 3
    random_flip: true
    rescaled: true
    num_workers: 2
    num_classes: 10
    num_train: 50000
    num_test: 10000

model:
    model_type: "ddpm"
    type: "simple"
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 2, 2, 2]
    num_res_blocks: 4
    attn_resolutions: [16, ]
    dropout: 0.1
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True
    resamp_with_conv: True
    fir: True
    fir_kernel: [1,3,3,1]
    skip_rescale: True
    resblock_type: 'biggan'
    progressive: 'none'
    progressive_input: 'residual'
    embedding_type: 'positional'
    conditional: True


Diffusion:
    alpha: 1.5
    beta_min: 0.1
    beta_max: 15.0
    clamp: 20.
    cosine_s: 0.008
    cosine_beta_max: 999.
    schedule: 'cosine'
    num_diffusion_timesteps: 1000

training:
    batch_size: 64
    n_epochs: 2001
    num_steps: 1000
    path: null
    device: 'cuda'
    training_clamp: 100
    initial_epoch: 0
    sample_probs: [0,0.2,0,0,0,0,0,0.8,0,0]
    conditional: True
    fix_class: null
    fid_mode: 'train'
    ckpt_store: 10
    sampling_store: 100
    store_path: "/scratch/private/eunbiyoon/Levy"


sampling:
    sampling_steps: 500 # integer 1~
    sampler: 'pc_sampler2' #pc_sampler2, ode_sampler
    batch_size: 100
    initial_clamp: 20
    clamp: 20
    fix_class: null # null or integer
    trajectory: False
    device: 'cuda'
    path: "/scratch/private/eunbiyoon/levy/assert/CIFAR10_15_NCSNPP.pth"
    dir_path: "/scratch/private/eunbiyoon/levy"

sample_fid:
    sampler: 'pc_sampler2'
    num_steps: 500
    device: 'cuda'


optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0001
    mu: 0.9999
    grad_clip: 1.0